<a href="https://colab.research.google.com/github/COBR-A/prabhat/blob/main/python_practice3npy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a python program to insert a new number at the given
position
* in a list of numbers without using insert function.
* lst=[1,2,3,4,5,6,7]
* num=10
* pos=2
* [1,2,10,3,4,5,6,7]

In [ ]:
n=int(input("Enter the no. of elements in the list: "))
lst=[]
for i in range(n):
  n1=int(input("Enter elements "))
  lst.append(n1)
print("The original list: ", lst)
num=int(input("Enter the no. to be inserted in the list: "))
pos=int(input("Enter the position where the element is to be inserted: "))
#lst[pos:pos]=[num]
lst = lst[:pos] + [num] + lst[pos:]
print("The updated list is : ", lst)

write a python program to create a tuple of email ids entered by the user.
Create two separate tuples containing username and domain separately.
display all the three tuples
* n=3
* t1 = ("abc@gmail.com", "xyzpqr@yahoo.com", "qwert@dw.balbharati.org")
* t2 =("abc","xyz","qwe")
* t3 =("gmail.com", "yahoo.com", "dw.balbharati.org")

In [ ]:
t1=tuple()
t2=tuple()
t3=tuple()
n=int(input("Enter the number of email ids you want to input: "))
for i in range(n):
  email=input("Enter the emailid: ")
  t1=t1+(email,)
  lst=email.split("@")
  t2=t2+ (lst[0],)
  t3=t3 +(lst[1],)

print("The emailids are: ", t1)
print("the usrenames are: ", t2)
print("the domain names are: ", t3)

write python program to create a list and search the given element in the list.
* also print the position of the number. Print error msg if the number not found
* donot use index() or find()

In [ ]:
n=int(input("Enter the number of elements in the list: "))
lst=[]
for i in range(n):
  n1=int(input("Enter the list element:"))
  lst.append(n1)
num=int(input("Enter the number to be searched:"))
flag=0
for i in range(n):
  if lst[i]==num:
    print("the number is present at ", i+1," position")
    flag=1
if flag==0:
  print("Number not found")

# **numpy**

In [ ]:
import numpy as np
lst1=[1,2,3,4]
lst2=[5,6,7,8]
lst3=[20,11,0,1]
arr=np.array([lst1,lst2,lst3])
arr

In [ ]:
arr1=np.array((9,8,7,6))
arr1

In [ ]:
arr1[1: ] #start from  element located at index 1


In [ ]:
arr1[:1]# start but end at location 1 but dont include index 1


In [ ]:
arr[1:, 1:]

In [ ]:
arr1[::2] #start,end, stepsize

In [ ]:
a1=arr.reshape(4,3)
a1

In [ ]:
a1[1:2,:2]
a1+=1

In [ ]:
#Exploratory Data Analysis
arr
arr[arr<12]

In [ ]:
##mechanism to create an array
np.arange(1,20,2).reshape(2,5)

In [ ]:
##mechanism to create a 1D array
np.arange(1,20,2).reshape(2,5,1)

In [ ]:
arr1*arr1

In [ ]:
np.ones((5,4))

In [ ]:
np.zeros((4,5))

In [ ]:
np.random.randint(10,50,4).reshape(2,2)


In [ ]:
np.random.randn(5,6)

# **pandasss**

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),
                index=["Row1", "Row2", "Row3", "Row4", "Row5"  ],
                columns=["column1","column2", "column3", "column4"])

NameError: name 'pd' is not defined

In [ ]:
df.head()


column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.tail()


column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
##using row index name loc
df.loc[['Row3','Row4']]


column1  column2  column3  column4
Row3        8        9       10       11
Row4       12       13       14       15

In [ ]:
df.iloc[2:4,0:2]


column1  column2
Row3        8        9
Row4       12       13

In [ ]:
df.iloc[2:,1:]

column2  column3  column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [ ]:
##convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [ ]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1","Row2"],
                columns=["Column1","Column2","Column3",])


In [ ]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

6 apr


In [ ]:

a4=np.random.randint(0,100,20).reshape(4,5)
print(a4)

[[16 85 30 60 28]
 [83 79 23 94 38]
 [70 76 62 16  2]
 [31 34 36 92 29]]


In [ ]:
a4=np.arange(0,20).reshape(4,5)
print(a4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
a4=np.arange(0,100).reshape(10,10)
print(a4)
print(   )

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]



In [ ]:
a4[5:6,3:8]
a4[9:1,9:1]
a4[::-1]

In [ ]:
df=pd.DataFrame(data=np.arange(0,20).reshape(4,5),index=["row1","row2","row3","row4"],
             columns=["col1","col2","col3","col4","col5"])

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
df

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [ ]:
df.head()

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [ ]:
df.tail(-1)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive

/content/drive/MyDrive


In [ ]:
#pd.set_option('display.max_columns', 15)
da1=pd.read_csv('/content/drive/MyDrive/batc5152intern.csv')

In [ ]:
da1

SAP ID         PROG    Enroll No             NAME  \
0   500119692  BTCSE 2023  R2142231727    ANIRUDH BHATT   
1   500121151  BTCSE 2023  R2142231728  ABHINAV DWIVEDI   
2   500121447  BTCSE 2023  R2142231729      ADITYA JAIN   
3   500119713  BTCSE 2023  R2142231730   RUDRAKSH RAWAT   
4   500121825  BTCSE 2023  R2142231731    VIRAJ BHIDOLA   
..        ...         ...          ...              ...   
83  500126863  BTCSE 2023     R2142231    Hardik Sindhu   
84  500126799  BTCSE 2023     R2142231      Anjali soni   
85  500127057  BTCSE 2023     R2142231   Vaibhav Panwar   
86      50012  BTCSE 2023     R2142231   Saransh Sharma   
87  500127120  BTCSE 2023     R2142231  Brishav debnath   

                          Email id  Batch Number PRERNA s-1 PRERNA S-2  
0    Anirudh.119692@stu.upes.ac.in  BT-CSE-I-B51          P          P  
1    Abhinav.121151@stu.upes.ac.in  BT-CSE-I-B51         AB         AB  
2     Aditya.121447@stu.upes.ac.in  BT-CSE-I-B51          P         AB  
3   Rudraksh.119713@stu.upes.ac.in  BT-CSE-I-B51         AB         AB  
4      Viraj.121825@stu.upes.ac.in  BT-CSE-I-B51          P         AB  
..                             ...           ...        ...        ...  
83    Hardik.126863@stu.upes.ac.in  BT-CSE-I-B51          p          P  
84    Anjali.126799@stu.upes.ac.in  BT-CSE-I-B52          P          P  
85   Vaibhav.127057@stu.upes.ac.in  BT-CSE-I-B51          p          P  
86                             NaN  BT-CSE-I-B51          p          P  
87   Brishav.127120@stu.upes.ac.in  BT-CSE-I-B51          p          P  

[88 rows x 8 columns]

# wap to create a data set of 12 row and 14 colums decorate it with with diffirent names


In [ ]:
df=pd.DataFrame(data=np.random.randint(0,200,168).reshape(12,14),index=["prabhat","shivam","shubham","harsh","kanha","sristi","kanak","ayesha","nautiyal","vaibhav","boss","dk"],
             columns=["c1","c2","c3","c4","c5","c6","c7","c8","c9","c10","c11","c12","c13","c14"])

In [ ]:
df

c1   c2   c3   c4   c5   c6   c7   c8   c9  c10  c11  c12  c13  c14
prabhat   166   64    9   85  129  116  149  175  120  170   38    6   12  113
shivam     36   65  108   44   76   53  139   95  183   75   85  107  170  192
shubham   138   17   83  171  130  122   10  112  154  151  114  113   90  124
harsh      40  111  178    2  139  178  119   91  191   44   31   98   98  188
kanha      10    7  160  130   31  147   87  183  181  162  193  157   62  161
sristi     23  153   89   80  175  127  128   24   91   73   59   51   97   62
kanak     163  165  141  104   18  141   17   57  197  177  176  152   58  195
ayesha     57   92   95   20    7   33  102   12   94  111  173  199  123  127
nautiyal  114    1  188  106   10   99  124  126   29   90    4  127  198  163
vaibhav   167  169  158  149  175   20   75   55   86  105  111  165  182   46
boss       27  162    8   32  123   54   29   69   16  112    2  147  156   71
dk        110   33  179   93   13  140   83   92  164   25   40   84  165  130

In [ ]:
df.head()

c1   c2   c3   c4   c5   c6   c7   c8   c9  c10  c11  c12  c13  c14
prabhat  166   64    9   85  129  116  149  175  120  170   38    6   12  113
shivam    36   65  108   44   76   53  139   95  183   75   85  107  170  192
shubham  138   17   83  171  130  122   10  112  154  151  114  113   90  124
harsh     40  111  178    2  139  178  119   91  191   44   31   98   98  188
kanha     10    7  160  130   31  147   87  183  181  162  193  157   62  161

In [ ]:
df.tail()

c1   c2   c3   c4   c5   c6   c7   c8   c9  c10  c11  c12  c13  c14
ayesha     57   92   95   20    7   33  102   12   94  111  173  199  123  127
nautiyal  114    1  188  106   10   99  124  126   29   90    4  127  198  163
vaibhav   167  169  158  149  175   20   75   55   86  105  111  165  182   46
boss       27  162    8   32  123   54   29   69   16  112    2  147  156   71
dk        110   33  179   93   13  140   83   92  164   25   40   84  165  130

In [ ]:
import seaborn as sns
sns.pairplot(da1, hue='2')

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

books = [
    ("00AW", "Wings of Fire", "Abdul Kalam", 214.99),
    ("01IM", "Ignited Minds", "Abdul Kalam", 213.50),
    ("02IV", "India 2020: A Vision for the New Millennium", "Abdul Kalam", 212.75),
    ("03MJ", "My Journey: Transforming Dreams into Actions", "Abdul Kalam", 215.25),
    ("04IM", "The Immortals of Meluha", "Amish Tripathi", 314.99),
    ("05SN", "The Secret of the Nagas", "Amish Tripathi", 313.50),
    ("06OV", "The Oath of the Vayuputras", "Amish Tripathi", 312.75),
    ("07SI", "Scion of Ikshvaku", "Amish Tripathi", 315.25),
    ("08SB", "A Suitable Boy", "Vikram Seth", 215.50),
    ("09MC", "Midnight's Children", "Salman Rushdie", 514.75),
    ("10WT", "The White Tiger", "Aravind Adiga", 311.25),
    ("11TG", "The Guide", "R.K. Narayan", 510.99),
    ("12TP", "Train to Pakistan", "Khushwant Singh", 193.80),
    ("13PC", "Python Crash Course", "Eric Matthes", 225.00),
    ("14IA", "Introduction to Algorithms", "Thomas H. Cormen", 445.00),
    ("15HD", "Head First Design Patterns", "Eric Freeman", 340.00),
    ("16JG", "JavaScript: The Good Parts", "Douglas Crockford", 520.00)
]

dp=np.array(books)
df = pd.DataFrame(data=np.array(books), columns=["book_id","book name","author","price"])
df


book_id                                     book name             author  \
0     00AW                                 Wings of Fire        Abdul Kalam   
1     01IM                                 Ignited Minds        Abdul Kalam   
2     02IV   India 2020: A Vision for the New Millennium        Abdul Kalam   
3     03MJ  My Journey: Transforming Dreams into Actions        Abdul Kalam   
4     04IM                       The Immortals of Meluha     Amish Tripathi   
5     05SN                       The Secret of the Nagas     Amish Tripathi   
6     06OV                    The Oath of the Vayuputras     Amish Tripathi   
7     07SI                             Scion of Ikshvaku     Amish Tripathi   
8     08SB                                A Suitable Boy        Vikram Seth   
9     09MC                           Midnight's Children     Salman Rushdie   
10    10WT                               The White Tiger      Aravind Adiga   
11    11TG                                     The Guide       R.K. Narayan   
12    12TP                             Train to Pakistan    Khushwant Singh   
13    13PC                           Python Crash Course       Eric Matthes   
14    14IA                    Introduction to Algorithms   Thomas H. Cormen   
15    15HD                    Head First Design Patterns       Eric Freeman   
16    16JG                    JavaScript: The Good Parts  Douglas Crockford   

     price  
0   214.99  
1    213.5  
2   212.75  
3   215.25  
4   314.99  
5    313.5  
6   312.75  
7   315.25  
8    215.5  
9   514.75  
10  311.25  
11  510.99  
12   193.8  
13   225.0  
14   445.0  
15   340.0  
16   520.0